# Generated by Django 4.2 on 2025-04-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("task_queue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrontabSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minute",
                    models.CharField(
                        default="*",
                        help_text="Minute field, e.g. '*' or '0,15,30,45'",
                        max_length=64,
                    ),
                ),
                (
                    "hour",
                    models.CharField(
                        default="*",
                        help_text="Hour field, e.g. '*' or '0,12'",
                        max_length=64,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        default="*",
                        help_text="Day of week field, e.g. '*' or 'mon-fri'",
                        max_length=64,
                    ),
                ),
                (
                    "day_of_month",
                    models.CharField(
                        default="*",
                        help_text="Day of month field, e.g. '*' or '1,15'",
                        max_length=64,
                    ),
                ),
                (
                    "month_of_year",
                    models.CharField(
                        default="*",
                        help_text="Month of year field, e.g. '*' or '1,6,12'",
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeriodicTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for the periodic task.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="Name of the registered task function to be executed.",
                        max_length=255,
                    ),
                ),
                (
                    "arguments",
                    models.JSONField(
                        default=list,
                        help_text="List of positional arguments for the task.",
                    ),
                ),
                (
                    "kwargs",
                    models.JSONField(
                        default=dict,
                        help_text="Dictionary of keyword arguments for the task.",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("total_run_count", models.PositiveIntegerField(default=0)),
                (
                    "crontab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodic_tasks",
                        to="task_queue.crontabschedule",
                    ),
                ),
            ],
        ),
    ]
